version: '3.8'

services:
  db:
    container_name: authentication_db_go
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/db-data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - authentication_go
  app:
    container_name: authentication_app_go
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - authentication_go

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
#      REDIS_USERNAME: redis
#      REDIS_DISABLE_DEFAULT_USER: true

volumes:
  authentication:
  db-data:

networks:
  authentication_go:
